<?php
/**
 * 业务处理类
 */
namespace api\components;

use common\components\Helper;
use yii;
use yii\base\Exception;

class apiHelper extends Helper
{
    public static function factory()
    {
        return parent::factory(); // TODO: Change the autogenerated stub
    }
}
