<?php
namespace api\controllers;

use common\components\WechatCoreHelper;
use Yii;
use yii\base\Exception;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public $postObj;//接收微信请求数据

    public function beforeAction($action)
    {
        try
        {
            //you must define TOKEN by yourself
            if (!defined("WECHAT_TOKEN")) {
                throw new Exception('TOKEN is not defined!');
            }

            $this->postObj = new \stdClass();
            //验证
            WechatCoreHelper::factory()->valid(WECHAT_TOKEN);

            $postStr = $GLOBALS ["HTTP_RAW_POST_DATA"];
            /* 防xml注入 */
            libxml_disable_entity_loader ( true );
            if (! empty ( $postStr )) {
                $this->postObj = simplexml_load_string ( $postStr, 'SimpleXMLElement', LIBXML_NOCDATA );
                if (empty ( $this->postObj )) {
                    die ( 'poststr not null' );
                }else{
                    define ( 'FROM_USER_NAME', $this->postObj->FromUserName );//发送方帐号（用户OpenID） 接收到的数据
                    define ( 'TO_USER_NAME', $this->postObj->ToUserName );//开发者微信号
                    define ( 'MSG_TYPE', $this->postObj->MsgType );//消息类型
                }
            } else {
                die ( '' );
            }
        } catch (Exception $e) {
            throw new Exception('500');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function actionIndex()
    {
        $sendModel = new PUserSendMsg();
        if ('text' == MSG_TYPE) {
            //文本信息
            $sendModel->matchSendContent($this->postObj->Content);
            exit;
        }elseif ('image' == MSG_TYPE){
            //图片信息
        }elseif ('location' == MSG_TYPE){
            //地理信息
        }elseif ('event' == MSG_TYPE) {
            $event = $this->postObj->Event;//触发事件	 使用FromUserName + CreateTime 排重
            $userModel = new PUserInfo();

            if ('subscribe' == $event) {
                //用户关注  更新用户数据表信息
                $userInfo = $userModel->getUserInfo( FROM_USER_NAME );//取得用户详细信息
                if (isset($userInfo['openid'])){
                    //WechatCoreHelper::wechatLog($userInfo,'vrpeng003','err',new VrpengWechatLog() );
                    $userModel->updateUserInfo($userInfo);
                }else{
                    WechatCoreHelper::wechatLog($userInfo,'vrpeng001','err',new VrpengWechatLog() );
                }
                $sendModel->sendSubscribeContent();

            } elseif ($event == 'unsubscribe') {
                //取消关注   相关数据操作
                $userModel->updateSubscribeState( FROM_USER_NAME );

            } elseif ($event == 'CLICK') {
                //自定义菜单推送
                $eventKey = $this->postObj->EventKey;
                if ($eventKey == 'time') {

                }
            }
        }

        exit('success');
    }

}
